use thiserror::Error;
pub const AUDIO_MAGIC:&[u8;4]=b"EIAU";pub const HEARTBEAT_MAGIC:&[u8;4]=b"EIHB";pub const CONTROL_MAGIC:&[u8;4]=b"EICC";pub const ACK_MAGIC:&[u8;4]=b"EICA";pub const AUDIO_HEADER_LEN:usize=32;
#[derive(Debug,Error,PartialEq)]pub enum AudioError{#[error("数据包过短")]Short,#[error("magic 无效")]Magic,#[error("协议版本不支持")]Version,#[error("音频格式无效")]Format,#[error("payload 长度不匹配")]Length}
#[derive(Debug,Clone,PartialEq)]pub struct AudioPacket<'a>{pub session_id:u32,pub sequence:u32,pub sample_rate:u32,pub timestamp_us:u64,pub frame_samples:u16,pub payload:&'a[u8]}
pub fn parse_audio(raw:&[u8])->Result<AudioPacket<'_>,AudioError>{if raw.len()<AUDIO_HEADER_LEN{return Err(AudioError::Short)}if &raw[0..4]!=AUDIO_MAGIC{return Err(AudioError::Magic)}if raw[4]!=2{return Err(AudioError::Version)}let session_id=u32::from_le_bytes(raw[8..12].try_into().unwrap());let sequence=u32::from_le_bytes(raw[12..16].try_into().unwrap());let sample_rate=u32::from_le_bytes(raw[16..20].try_into().unwrap());let timestamp_us=u64::from_le_bytes(raw[20..28].try_into().unwrap());let frame_samples=u16::from_le_bytes(raw[28..30].try_into().unwrap());let payload_len=u16::from_le_bytes(raw[30..32].try_into().unwrap())as usize;if sample_rate!=16000||frame_samples!=320{return Err(AudioError::Format)}if raw.len()!=AUDIO_HEADER_LEN+payload_len||payload_len!=frame_samples as usize*2{return Err(AudioError::Length)}Ok(AudioPacket{session_id,sequence,sample_rate,timestamp_us,frame_samples,payload:&raw[32..]})}
#[derive(Debug,Copy,Clone)]pub enum ControlAction{Start=1,Stop=2,Keepalive=3}
pub fn control_packet(action:ControlAction,session_id:u32,token:[u8;16])->[u8;36]{let mut out=[0u8;36];out[0..4].copy_from_slice(CONTROL_MAGIC);out[4]=1;out[5]=action as u8;out[8..12].copy_from_slice(&session_id.to_le_bytes());out[20..36].copy_from_slice(&token);out}
pub fn heartbeat_flags(raw:&[u8])->Result<u32,AudioError>{if raw.len()!=20{return Err(AudioError::Short)}if &raw[0..4]!=HEARTBEAT_MAGIC{return Err(AudioError::Magic)}if raw[4]!=1{return Err(AudioError::Version)}Ok(u32::from_le_bytes(raw[8..12].try_into().unwrap()))}

#[cfg(test)]mod tests{use super::*;#[test]fn parses_audio_golden_vector(){let mut packet=vec![0u8;672];packet[0..4].copy_from_slice(AUDIO_MAGIC);packet[4]=2;packet[8..12].copy_from_slice(&42u32.to_le_bytes());packet[12..16].copy_from_slice(&7u32.to_le_bytes());packet[16..20].copy_from_slice(&16000u32.to_le_bytes());packet[20..28].copy_from_slice(&1234u64.to_le_bytes());packet[28..30].copy_from_slice(&320u16.to_le_bytes());packet[30..32].copy_from_slice(&640u16.to_le_bytes());let parsed=parse_audio(&packet).unwrap();assert_eq!(parsed.session_id,42);assert_eq!(parsed.sequence,7);assert_eq!(parsed.payload.len(),640)}#[test]fn control_is_little_endian(){let p=control_packet(ControlAction::Start,0x01020304,[9;16]);assert_eq!(&p[8..12],&[4,3,2,1]);assert_eq!(&p[20..36],&[9;16])}}
